import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

import type { WebApplication, WithContext } from "schema-dts";

import "./globals.css";
import Header from "@/components/header";
import Script from "next/script";

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const schemaJSONLD: WithContext<WebApplication> = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: "Reading Time Estimator | Calculate Reading Times Quickly",
    url: "https://www.example.com",
    applicationCategory: "Utility",
    operatingSystem: "All",
    browserRequirements: "Requires JavaScript",
    description:
      "Reading time estimator: Calculate the time needed to read a specific text. Useful tool that estimates the reading time of a specific text. Rely on accademic studies about the average reading speed.",
    offers: {
      "@type": "Offer",
      price: 0,
    },
  };

  return (
    <html lang="en">
      <head>
        <meta name="google-adsense-account" content="ca-pub-7098826907138268" />
        <script
          defer
          src="https://cloud.umami.is/script.js"
          data-website-id="80d27b72-56d2-4867-8529-f8894b053e11"
        ></script>
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7098826907138268"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body className={`${robotoMono.className} antialiased`}>
        <Script
          id="web-app-schema"
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(schemaJSONLD),
          }}
        />
        <Header />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
